version: '3'

services:
  db:
     image: 'postgres'
     restart: always
     ports:
       # if you want to expose the postgres instance to a tool on localhost, use this instead:
       # see: https://stackoverflow.com/a/55259785
       # - '6543:5432'
       - '5432'
     environment:
      - POSTGRES_DB=makeability
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
     volumes:
      - postgres-data:/var/lib/postgresql/data
  website:    
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '127.0.0.1:8571:8000'
    volumes:
      - .:/code
    depends_on:
      - db
    command: ["./docker-entrypoint.sh", "db", "python", "manage.py"]
    links:
      - "db:database"
volumes:
    postgres-data:   
