version: '3'

services:
  db:
    image: "${POSTGRES_IMAGE:-postgres}" # Can be set in rebuildanddeploy.sh, or defaults to: https://hub.docker.com/_/postgres
    restart: always
    ports:
      - '127.0.0.1:8623:5432'
    environment:
      - POSTGRES_DB=makeability
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data
  website:
    environment:
      - DJANGO_ENV=${DJANGO_ENV:-TEST}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '127.0.0.1:8571:8000'
    volumes:
      - .:/code
      - ${MEDIA_PATH:-./media}:/code/media
      - ${CONFIG_PATH:-./config-dev.ini}:/code/config.ini # for loading vars into ConfigParser in Django
    depends_on:
      - db
    command: ["./docker-entrypoint.sh", "db", "python", "manage.py"]
    links:
      - "db:database"
volumes:
  db-data:
    external:
      name: "makeabilitylabcswashingtonedu_${POSTGRES_VOLUME:-postgres-data}"
