# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(choices=[('High School', 'High School Research Assistant'), ('UGrad', 'Undergraduate Research Assistant'), ('MS Grad', 'MS Researcher'), ('PhD Grad', 'PhD Researcher'), ('Post Doc', 'Post Doc'), ('Assistant Prof', 'Assistant Professor'), ('Associate Prof', 'Associate Professor'), ('Professor', 'Professor')], default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('personal_website', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=website.models.UniquePathAndRename('person', True))),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Member', 'Member'), ('Collaborator', 'Collaborator')], default='Member', max_length=50)),
                ('title', models.CharField(choices=[('High School', 'High School Research Assistant'), ('UGrad', 'Undergraduate Research Assistant'), ('MS Grad', 'MS Researcher'), ('PhD Grad', 'PhD Researcher'), ('Post Doc', 'Post-doctoral Researcher'), ('Assistant Prof', 'Assistant Professor'), ('Associate Prof', 'Associate Professor'), ('Professor', 'Professor')], max_length=50)),
                ('department', models.CharField(default='Computer Science', max_length=50)),
                ('university', models.CharField(default='University of Maryland', max_length=60)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.ManyToManyField(to='website.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.ManyToManyField(to='website.Person')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Person'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Person'),
        ),
    ]
