# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20151218_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='person',
        ),
        migrations.RemoveField(
            model_name='member',
            name='person',
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(choices=[('High School Student', 'High School Student'), ('Undergrad', 'Undergrad'), ('MS Student', 'MS Student'), ('PhD Student', 'PhD Student'), ('Post-doc', 'Post-doc'), ('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Collaborator',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
