# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20151218_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='authors',
        ),
        migrations.AddField(
            model_name='talk',
            name='pdf_file',
            field=models.FileField(default=None, null=True, upload_to='talks/'),
        ),
        migrations.AddField(
            model_name='talk',
            name='thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to='', verbose_name='talks/images/'),
        ),
    ]
