# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20151219_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='talk',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='forum_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='forum_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='raw_file',
            field=models.FileField(default=None, null=True, upload_to='talks/'),
        ),
        migrations.AddField(
            model_name='talk',
            name='slideshare_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='speakers',
            field=models.ManyToManyField(null=True, to='website.Person'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to='talks/images/'),
        ),
        migrations.AddField(
            model_name='talk',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='website.Project'),
        ),
    ]
