# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20151221_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_file', models.FileField(default=None, null=True, upload_to='posters/')),
                ('raw_file', models.FileField(default=None, null=True, upload_to='posters/')),
                ('thumbnail', models.ImageField(editable=False, null=True, upload_to='posters/images/')),
                ('authors', models.ManyToManyField(blank=True, null=True, to='website.Person')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='pdf_file',
            field=models.FileField(default=None, null=True, upload_to='talks/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='award',
            field=models.CharField(blank=True, choices=[('Best Paper Award', 'Best Paper Award'), ('Honorable Mention', 'Honorable Mention'), ('Best Paper Nominee', 'Best Paper Nominee')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='page_num_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='page_num_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='total_papers_admitted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='total_papers_submitted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='raw_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='talks/'),
        ),
        migrations.AddField(
            model_name='poster',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Publication'),
        ),
    ]
