# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20151221_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to='talks/images/'),
        ),
    ]
