# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_publication_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='book_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='book_title_short',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
