# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20151221_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='total_papers_admitted',
            new_name='total_papers_accepted',
        ),
    ]
