# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 22:36
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_person_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '600x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
