# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields
import website.utils.fileutils


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20160510_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, to='website.Keyword'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '245x245', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, help_text='You must select "Save and continue editing" at the bottom of the page after uploading a new image for cropping.', upload_to=website.utils.fileutils.UniquePathAndRename('person', True)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdf_file',
            field=models.FileField(default=None, upload_to='publications/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to='publications/images/'),
        ),
    ]
