# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 16:47
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields

from sortedm2m.operations import AlterSortedManyToManyField

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20160513_1157'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='publication',
            name='authors',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='website.Person'),
        ),
    ]
