# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20160513_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationAuthorThroughModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Person')),
            ],
            options={
                'ordering': ('publication', 'order'),
            },
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(through='website.PublicationAuthorThroughModel', to='website.Person'),
        ),
        migrations.AddField(
            model_name='publicationauthorthroughmodel',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Publication'),
        ),
    ]
