# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20160514_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='authors',
        ),
        migrations.AddField(
            model_name='publication',
            name='authorsOrdered',
            field=models.ManyToManyField(through='website.PublicationAuthorThroughModel', to='website.Person'),
        ),
    ]
