# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 16:56
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields

from sortedm2m.operations import AlterSortedManyToManyField

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20160514_1247'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='publication',
            name='keywords',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, to='website.Keyword'),
        ),
        AlterSortedManyToManyField(
            model_name='publication',
            name='projects',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, to='website.Project'),
        ),
    ]
