# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import website.utils.fileutils


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20160514_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, help_text='You must select "Save and continue editing" at the bottom of the page after uploading a new image for cropping.', max_length=255, upload_to=website.utils.fileutils.UniquePathAndRename('person', True)),
        ),
        migrations.AlterField(
            model_name='poster',
            name='pdf_file',
            field=models.FileField(default=None, max_length=255, null=True, upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='raw_file',
            field=models.FileField(default=None, max_length=255, null=True, upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='thumbnail',
            field=models.ImageField(editable=False, max_length=255, null=True, upload_to='posters/images/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdf_file',
            field=models.FileField(default=None, max_length=255, upload_to='publications/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='thumbnail',
            field=models.ImageField(editable=False, max_length=255, null=True, upload_to='publications/images/'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='pdf_file',
            field=models.FileField(default=None, max_length=255, null=True, upload_to='talks/'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='raw_file',
            field=models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='talks/'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='thumbnail',
            field=models.ImageField(editable=False, max_length=255, null=True, upload_to='talks/images/'),
        ),
    ]
